version: "3"
services:
  wakatime-sync:
    image: wf2311/wakatime-sync:1.0
    container_name: wakatime-sync
    environment:
      - JAVA_OPTS=-Xmx256m -Xms64m -Xss256k
      - SERVER_PORT=3040
      - WAKATIME_APP_KEY=a1873785-1b97-4ce0-bcdd-6b91351b238e
      - WAKATIME_PROXY_URL=false
      - WAKATIME_FTQQ_KEY=SCU39084T628931174fcf33b8a6fbd30cd35cbd4d5c34cd3fa50a3
      - WAKATIME_DINGDING_KEY=8e8242739200aadf3ed4d007cc15ce9774b73588beb567731cefbfb2d15c6ea7
      - START_DAY=2016-02-01
      - MYSQL_URL=jdbc:mysql://49.234.89.76:3306/wakatime?characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=PRC
      - MYSQL_USERNAME=wakatime
      - MYSQL_PASSWORD=WK1357!&!
    volumes:
      - ~/Share/logs/wakatime-sync/:/application/logs
    ports:
      - "3040:3040"