version: "3"
services:
  wakatime-sync:
    build: .
    container_name: wakatime-sync
    restart: unless-stopped
    environment:
      - "JAVA_OPTS=-Xmx256m -Xms64m -Xss256k"
      - "SERVER_PORT=${SERVER_PORT}"
      - "WAKATIME_APP_KEY=${WAKATIME_APP_KEY}"
      - "WAKATIME_PROXY_URL=${WAKATIME_PROXY_URL}"
      - "START_DAY=${START_DAY}"
      - "MYSQL_URL=jdbc:mysql://${MYSQL_HOST}/wakatime_db?characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=PRC"
      - "MYSQL_USERNAME=${MYSQL_USERNAME}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    volumes:
      - "./logs:/application/logs"
      - "${HOME}/.m2:/root/.m2"
    expose:
      - "3040:3040"
    extra_hosts:
      - "host.docker.internal:host-gateway"
