version: "3"
services:
  wakatime-sync:
    build: .
    container_name: wakatime-sync
    restart: unless-stopped
    networks:
      - traefik-global-proxy
    command:
      - "-Xmx256m"
      - "-Xms64m" 
      - "-Xss256k"
      - "-Dspring.datasource.url=jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}?characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=PRC"
      - "-Dspring.datasource.username=${MYSQL_USERNAME}"
      - "-Dspring.datasource.password=${MYSQL_PASSWORD}"
      - "-Dwakatime.secret-api-key=${WAKATIME_APP_KEY}"
      - "-Dwakatime.proxy-url=${WAKATIME_PROXY_URL}"
      - "-Dwakatime.start-day=${START_DAY}"
      - "-Dwakatime.ftqq-key=${WAKATIME_FTQQ_KEY}"
      - "-Dwakatime.dingding-key=${WAKATIME_DINGDING_KEY}"
      - "-Dserver.port=${SERVER_PORT}"
      - "org.springframework.boot.loader.JarLauncher"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wakatime-sync.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.wakatime-sync.entrypoints=web"
      - "traefik.http.services.wakatime-sync.loadbalancer.server.port=${SERVER_PORT}"
      - "traefik.http.routers.wakatime-sync.middlewares=wakatime-sync-compress"
      - "traefik.http.middlewares.wakatime-sync-compress.compress=true"
    volumes:
      - "./logs:/application/logs"
      - "${HOME}/.m2:/root/.m2"
    expose:
      - "${SERVER_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  traefik-global-proxy:
    external: true